name: tst_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - anaconda
  - conda-forge
dependencies:
  - rmg == 2.4.0
  - ase
  - cclib == 1.5.3
  - py3dmol
  - rdkit == 2018.09.3.0
  - nose
  - codecov
