name: tst_env
channels:
  - defaults
  - rdkit
  - krsna
  - rmg
  - cantera
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - rmg == 3.0.0
  - ase
  - cclib == 1.6.2 
  - py3dmol
  - rdkit >= 2019.03.4
  - nose
  - codecov
