name: tst_env
channels:
  - anaconda
  - rmg
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ase=3.22.1
  - biopython=1.79
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - cclib=1.7.2
  - certifi=2023.7.22
  - click=8.1.3
  - coolprop=6.4.1
  - cycler=0.11.0
  - expat=2.5.0
  - flask=2.2.3
  - fontconfig=2.14.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - gprof2dot=2017.9.19
  - icu=58.2
  - importlib-metadata=4.11.4
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.67.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.14
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libzlib=1.2.13
  - lpsolve=5.5.2.5
  - lpsolve55=5.5
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - munkres=1.1.4
  - ncurses=6.4
  - nose=1.3.7
  - numpy=1.21.6
  - openbabel=3.0.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=1.3.5
  - pcre2=10.40
  - periodictable=1.5.2
  - pillow=9.2.0
  - pip=23.2.1
  - pixman=0.38.0
  - pthread-stubs=0.4
  - py-boost=1.67.0
  - pydqed=1.0.3
  - pyparsing=3.1.0
  - pyrdl=1.1.2
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2023.3
  - quantities=0.12.3
  - rdkit=2020.03.3.0
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.42.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - unicodedata2=14.0.0
  - werkzeug=2.2.3
  - wheel=0.41.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - py3dmol==2.0.3
