name: tst_env
channels:
  - rmg
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - algopy=0.5.7
  - ase=3.22.1
  - biopython=1.79
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cantera=2.6.0
  - cclib=1.7.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.3
  - conda=22.9.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - coolprop=6.4.1
  - cryptography=38.0.2
  - cycler=0.11.0
  - expat=2.5.0
  - fftw=3.3.9
  - flask=2.2.3
  - fmt=9.1.0
  - fontconfig=2.14.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - gmp=6.2.1
  - gprof2dot=2017.9.19
  - h5py=3.7.0
  - hdf5=1.12.2
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.1
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libboost=1.67.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcantera=2.6.0
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libzlib=1.2.13
  - lpsolve=5.5.2.5
  - lpsolve55=5.5
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - metis=5.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mpfr=4.2.0
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - nose=1.3.7
  - numdifftools=0.9.41
  - numexpr=2.8.4
  - numpy=1.21.6
  - openbabel=3.0.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=1.3.5
  - patsy=0.5.3
  - pcre2=10.40
  - periodictable=1.5.2
  - pillow=9.2.0
  - pip=23.2.1
  - pixman=0.38.0
  - psutil=5.9.3
  - pthread-stubs=0.4
  - py-boost=1.67.0
  - pyaml=23.5.9
  - pycosat=0.6.4
  - pycparser=2.21
  - pydas=1.0.3
  - pydqed=1.0.3
  - pyopenssl=23.2.0
  - pyparsing=3.1.0
  - pyrdl=1.1.2
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2023.3
  - pyyaml=6.0
  - quantities=0.12.3
  - rdkit=2020.03.3.0
  - readline=8.2
  - requests=2.31.0
  - ruamel_yaml=0.15.80
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.42.0
  - statsmodels=0.13.2
  - suitesparse=5.10.1
  - sundials=5.7.0
  - tbb=2021.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toolz=0.12.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - unicodedata2=14.0.0
  - urllib3=2.0.4
  - werkzeug=2.2.3
  - wheel=0.41.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstandard=0.18.0
  - zstd=1.5.2
  - pip:
    - py3dmol==2.0.3
