name: tst_env
channels:
  - defaults
  - rdkit
  - ampayne
  - rmg
  - cantera
  - anaconda
  - conda-forge
dependencies:
  - python >= 3.7
  - rmg
  - ase
  - cclib
  - py3dmol
  - rdkit == 2018.09.3.0
  - nose
  - codecov
