name: tst_env
channels:
  - defaults
  - cantera
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - rmg::rmg
  - conda-forge::ase
  - conda-forge::cclib >= 1.7.0
  - conda-forge::py3dmol
  - rmg::rdkit >= 2019.03.4
  - codecov
  - nose
  - matplotlib
  - pip:
    # The current version of descriptastorus on conda-forge is 2.6.0, which is not compatible with the version of scipy that is included with rmg
    - descriptastorus==2.6.0
