#!/usr/bin/env python
# encoding: utf-8

name = ""
shortDesc = u""
longDesc = u"""

"""
entry(
    index = 0,
    label = "H + C3H4 <=> H2 + C3H3",
    degeneracy = 1.0,
    kinetics = DistanceData(
        distances = {'d12': 1.29429, 'd13': 2.25818, 'd23': 0.964372},
        method = 'm062x/6-311+G(2df,2p)',
    ),
    rank = 3,
    shortDesc = u"""M06-2X/6-311+G(2df,2p) calculation via group additive TS generator.""",
)

entry(
    index = 1,
    label = "<Molecule "CCCC"> + <Molecule "[O]O"> <=> <Molecule "[CH2]CCC"> + <Molecule "OO">",
